services:
  - type: web
    name: business-network-app
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      # Serve static assets directly
      - type: rewrite
        source: /assets/(.*)
        destination: /assets/$1
      
      # Error handling
      - type: rewrite
        source: /error
        destination: /error.html
      
      # Static page for initial loading
      - type: rewrite
        source: /static
        destination: /static.html
      
      # All other routes go to index.html for SPA routing
      - type: rewrite
        source: /.*
        destination: /index.html
    
    headers:
      # Default headers for all routes
      - path: /.*
        name: Cache-Control
        value: no-cache
      
      # Headers for static assets
      - path: /assets/.*
        name: Cache-Control
        value: "public, max-age=31536000, immutable"
      
      # Security headers
      - path: /.*
        name: X-Content-Type-Options
        value: nosniff
      - path: /.*
        name: X-Frame-Options
        value: DENY
      - path: /.*
        name: X-XSS-Protection
        value: "1; mode=block"
      
      # CORS headers
      - path: /.*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /.*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS"
      - path: /.*
        name: Access-Control-Allow-Headers
        value: "X-Requested-With, Content-Type, Authorization"
    
    # Error pages
    errorPages:
      404: /error.html
      500: /error.html
    
    # Explicitly mark as SPA
    spa: true
    
    # Health check
    healthCheckPath: /static.html
